### ISSUE TITLE
auth-guards integration tests broken on main since #172; CI never runs test:integration

### ISSUE THREAD

**Issue by ajnoble** [ajnoble/snowgum#217]
Found while writing integration tests for #197 (PR #214).

Two related problems:

1. **3 tests in `src/lib/__tests__/auth-guards.integration.test.ts` fail on main.** Since #172, `requireSession`'s orphan branch issues `redirect("/")` for a signed-in user who is not an active member of the target org, so these tests now see a `NEXT_REDIRECT` throw instead of the `AuthError` they assert:
   - "throws UNAUTHORISED when signed-in user is not a member of the org"
   - "throws UNAUTHORISED for cross-tenant attempts (Alice is in Org A, not Org B)"
   - "throws UNAUTHORISED when membership row exists but is inactive"

   The tests should be updated to assert the redirect signal (the security property — no session returned — still holds; PR #214's download-auth test does this for the same branch), or the orphan branch reconsidered for non-page contexts.

2. **CI never runs the integration suite.** `.github/workflows/ci.yml` and `deploy.yml` run `npm run lint` / `npm test` / build only — `npm run test:integration` is absent, which is how the foundational auth-guard tests sat broken unnoticed. The pglite suite needs no external services, so adding a step to `ci.yml` should be cheap.
